language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- pypy
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq glpk
install:
- pip install .
script: pulptest
before_deploy:
- sudo apt-get install texlive-latex-extra
- sudo apt-get install dvipng
deploy:
  provider: pypi
  docs_dir: doc/build/html
  user: StuartMitchell
  password:
    secure: SVUU0MC4tLFS0EWqybpjWHKHumZ0qB6quhkvvx0pyfn4h6CIgZqhuWdSD/PJomlZp+dfqdQUVq3Tzl50UwQFG4OcBORJ+fVjxGJPkO5dpFsvtoNfBRNV9ZkYzMUx0djXxFKK2sVNqgI2O2sDvZk4eHDD09+mKtoSZ5XeT68Vqno=
  on:
    tags: true
    repo: coin-or/pulp
